version: '3.9'

services:
  app:
    container_name: marvel-app
    image: marvel-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - marvel-api
    volumes:
      - .:/app
      - /app/node_modules

networks:
  marvel-api:
    name: marvel-api

volumes:
  marvel-app:
    name: marvel-app
